//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wtKST.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KST_StartAsHere {
            get {
                return ((bool)(this["KST_StartAsHere"]));
            }
            set {
                this["KST_StartAsHere"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool KST_StartAsAway {
            get {
                return ((bool)(this["KST_StartAsAway"]));
            }
            set {
                this["KST_StartAsAway"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("www.on4kst.info")]
        public string KST_ServerName {
            get {
                return ((string)(this["KST_ServerName"]));
            }
            set {
                this["KST_ServerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("23001")]
        public string KST_ServerPort {
            get {
                return ((string)(this["KST_ServerPort"]));
            }
            set {
                this["KST_ServerPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KST_UserName {
            get {
                return ((string)(this["KST_UserName"]));
            }
            set {
                this["KST_UserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KST_Password {
            get {
                return ((string)(this["KST_Password"]));
            }
            set {
                this["KST_Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3 - Microwave")]
        public string KST_Chat {
            get {
                return ((string)(this["KST_Chat"]));
            }
            set {
                this["KST_Chat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KST_AutoConnect {
            get {
                return ((bool)(this["KST_AutoConnect"]));
            }
            set {
                this["KST_AutoConnect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\ProgramData\\\\Win-Test\\\\extras\\\\qrv.xdt")]
        public string WinTest_QRV_FileName {
            get {
                return ((string)(this["WinTest_QRV_FileName"]));
            }
            set {
                this["WinTest_QRV_FileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\ProgramData\\\\Win-Test\\\\cfg\\\\wt.ini")]
        public string WinTest_INI_FileName {
            get {
                return ((string)(this["WinTest_INI_FileName"]));
            }
            set {
                this["WinTest_INI_FileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("qrv.xml")]
        public string WinTest_QRV_Table_FileName {
            get {
                return ((string)(this["WinTest_QRV_Table_FileName"]));
            }
            set {
                this["WinTest_QRV_Table_FileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public string UpdateInterval {
            get {
                return ((string)(this["UpdateInterval"]));
            }
            set {
                this["UpdateInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool KST_ShowBalloon {
            get {
                return ((bool)(this["KST_ShowBalloon"]));
            }
            set {
                this["KST_ShowBalloon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20000")]
        public string AS_Planes_MinAlt {
            get {
                return ((string)(this["AS_Planes_MinAlt"]));
            }
            set {
                this["AS_Planes_MinAlt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public string AS_MinDist {
            get {
                return ((string)(this["AS_MinDist"]));
            }
            set {
                this["AS_MinDist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public string AS_MaxDist {
            get {
                return ((string)(this["AS_MaxDist"]));
            }
            set {
                this["AS_MaxDist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public string AS_SCPRadius {
            get {
                return ((string)(this["AS_SCPRadius"]));
            }
            set {
                this["AS_SCPRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AS_Active {
            get {
                return ((bool)(this["AS_Active"]));
            }
            set {
                this["AS_Active"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public string AS_PlaneRadius {
            get {
                return ((string)(this["AS_PlaneRadius"]));
            }
            set {
                this["AS_PlaneRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowBeacons {
            get {
                return ((bool)(this["ShowBeacons"]));
            }
            set {
                this["ShowBeacons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("beacons.lst")]
        public string BeaconFileName {
            get {
                return ((string)(this["BeaconFileName"]));
            }
            set {
                this["BeaconFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9871")]
        public int WinTest_Port {
            get {
                return ((int)(this["WinTest_Port"]));
            }
            set {
                this["WinTest_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9872")]
        public int AS_Port {
            get {
                return ((int)(this["AS_Port"]));
            }
            set {
                this["AS_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KST_Loc {
            get {
                return ((string)(this["KST_Loc"]));
            }
            set {
                this["KST_Loc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KST_Name {
            get {
                return ((string)(this["KST_Name"]));
            }
            set {
                this["KST_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WinTest_Activate {
            get {
                return ((bool)(this["WinTest_Activate"]));
            }
            set {
                this["WinTest_Activate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string AS_Timeout {
            get {
                return ((string)(this["AS_Timeout"]));
            }
            set {
                this["AS_Timeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KST")]
        public string AS_My_Name {
            get {
                return ((string)(this["AS_My_Name"]));
            }
            set {
                this["AS_My_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AS")]
        public string AS_Server_Name {
            get {
                return ((string)(this["AS_Server_Name"]));
            }
            set {
                this["AS_Server_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.2G")]
        public string AS_QRG {
            get {
                return ((string)(this["AS_QRG"]));
            }
            set {
                this["AS_QRG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point WindowLocation {
            get {
                return ((global::System.Drawing.Point)(this["WindowLocation"]));
            }
            set {
                this["WindowLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1220, 768")]
        public global::System.Drawing.Size WindowSize {
            get {
                return ((global::System.Drawing.Size)(this["WindowSize"]));
            }
            set {
                this["WindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Band_144 {
            get {
                return ((bool)(this["Band_144"]));
            }
            set {
                this["Band_144"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Band_432 {
            get {
                return ((bool)(this["Band_432"]));
            }
            set {
                this["Band_432"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Band_1296 {
            get {
                return ((bool)(this["Band_1296"]));
            }
            set {
                this["Band_1296"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Band_2320 {
            get {
                return ((bool)(this["Band_2320"]));
            }
            set {
                this["Band_2320"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Band_3400 {
            get {
                return ((bool)(this["Band_3400"]));
            }
            set {
                this["Band_3400"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Band_5760 {
            get {
                return ((bool)(this["Band_5760"]));
            }
            set {
                this["Band_5760"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Band_10368 {
            get {
                return ((bool)(this["Band_10368"]));
            }
            set {
                this["Band_10368"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Band_24GHz {
            get {
                return ((bool)(this["Band_24GHz"]));
            }
            set {
                this["Band_24GHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Band_47GHz {
            get {
                return ((bool)(this["Band_47GHz"]));
            }
            set {
                this["Band_47GHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Band_76GHz {
            get {
                return ((bool)(this["Band_76GHz"]));
            }
            set {
                this["Band_76GHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1200")]
        public string KST_MaxDist {
            get {
                return ((string)(this["KST_MaxDist"]));
            }
            set {
                this["KST_MaxDist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeRequired {
            get {
                return ((bool)(this["UpgradeRequired"]));
            }
            set {
                this["UpgradeRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KST_Show_Own_Messages {
            get {
                return ((bool)(this["KST_Show_Own_Messages"]));
            }
            set {
                this["KST_Show_Own_Messages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WindowSplitterDistance1 {
            get {
                return ((int)(this["WindowSplitterDistance1"]));
            }
            set {
                this["WindowSplitterDistance1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WindowSplitterDistance2 {
            get {
                return ((int)(this["WindowSplitterDistance2"]));
            }
            set {
                this["WindowSplitterDistance2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AS")]
        public string AS_Local_Name {
            get {
                return ((string)(this["AS_Local_Name"]));
            }
            set {
                this["AS_Local_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AS_Local_Active {
            get {
                return ((bool)(this["AS_Local_Active"]));
            }
            set {
                this["AS_Local_Active"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\CQ $CALL sked 23 cm ?")]
        public string KST_Macro_1 {
            get {
                return ((string)(this["KST_Macro_1"]));
            }
            set {
                this["KST_Macro_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\CQ $CALL pse QRG 23 cm?")]
        public string KST_Macro_2 {
            get {
                return ((string)(this["KST_Macro_2"]));
            }
            set {
                this["KST_Macro_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\CQ $CALL sked 13 cm ?")]
        public string KST_Macro_3 {
            get {
                return ((string)(this["KST_Macro_3"]));
            }
            set {
                this["KST_Macro_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\CQ $CALL pse QRG 13 cm?")]
        public string KST_Macro_4 {
            get {
                return ((string)(this["KST_Macro_4"]));
            }
            set {
                this["KST_Macro_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\CQ $CALL pse call $FREQ")]
        public string KST_Macro_5 {
            get {
                return ((string)(this["KST_Macro_5"]));
            }
            set {
                this["KST_Macro_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\CQ $CALL pse lsn $FREQ")]
        public string KST_Macro_6 {
            get {
                return ((string)(this["KST_Macro_6"]));
            }
            set {
                this["KST_Macro_6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool KST_M1 {
            get {
                return ((bool)(this["KST_M1"]));
            }
            set {
                this["KST_M1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool KST_M2 {
            get {
                return ((bool)(this["KST_M2"]));
            }
            set {
                this["KST_M2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool KST_M3 {
            get {
                return ((bool)(this["KST_M3"]));
            }
            set {
                this["KST_M3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool KST_M4 {
            get {
                return ((bool)(this["KST_M4"]));
            }
            set {
                this["KST_M4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool KST_M5 {
            get {
                return ((bool)(this["KST_M5"]));
            }
            set {
                this["KST_M5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool KST_M6 {
            get {
                return ((bool)(this["KST_M6"]));
            }
            set {
                this["KST_M6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\CQ $CALL in QSO nw, I meep u")]
        public string KST_Macro_7 {
            get {
                return ((string)(this["KST_Macro_7"]));
            }
            set {
                this["KST_Macro_7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\CQ $CALL in QSO nw, pse mee later")]
        public string KST_Macro_8 {
            get {
                return ((string)(this["KST_Macro_8"]));
            }
            set {
                this["KST_Macro_8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KST_Macro_9 {
            get {
                return ((string)(this["KST_Macro_9"]));
            }
            set {
                this["KST_Macro_9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KST_Macro_0 {
            get {
                return ((string)(this["KST_Macro_0"]));
            }
            set {
                this["KST_Macro_0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool KST_M7 {
            get {
                return ((bool)(this["KST_M7"]));
            }
            set {
                this["KST_M7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool KST_M8 {
            get {
                return ((bool)(this["KST_M8"]));
            }
            set {
                this["KST_M8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KST_M9 {
            get {
                return ((bool)(this["KST_M9"]));
            }
            set {
                this["KST_M9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KST_M0 {
            get {
                return ((bool)(this["KST_M0"]));
            }
            set {
                this["KST_M0"] = value;
            }
        }
    }
}
